### ISSUE TITLE
rich-text

### ISSUE THREAD

**Issue by dmonad** [y-js/y-richtext#1]
Because we are somehow parsing the functions of the [rich-text ot format ](https://github.com/ottypes/rich-text), we should name this repo (and all references) rich-text. We can use the short term `rt` (instead of rte).

If we do it right, then we maybe able to support any editor that build on that format (e.g. ACE I guess).

Any objections?

**Comment by cphyc** [comment]
Nope.

**Comment by cphyc** [comment]
I'm working on it.

**Comment by cphyc** [comment]
Should be closed with two last PR.
