### ISSUE TITLE
Invalid index thrown by quill

### ISSUE THREAD

**Issue by cphyc** [y-js/y-richtext#102]
Quill throws an invalid index when we try to apply `{ops: []}` to an empty quill editor.
We should check that we're not trying to apply that kind of operation.

**Comment by cphyc** [comment]
You can reproduce it by emptying a quill instance. In another browser, just do `quill.setContents({ops: []})` and you get the bug.

**Comment by cphyc** [comment]
I think that the issue is that quill cannot handle properly the fact that we want to put a cursor at position 0 even though quill has no content at all.

**Comment by dmonad** [comment]
[https://github.com/quilljs/quill/issues/357]

This was a quill issue in the develop branch
