### ISSUE TITLE
Create a testing environement for y-rich-text

### ISSUE THREAD

**Issue by cphyc** [y-js/y-richtext#11]
We should verify that the conversion to yjs basic types (ListManager and MapManager) do not loose information.

**Comment by dmonad** [comment]
Yjs has a test suite, which works as follows:
- You define all the actions that you can do on the type. 
- Then the test suite executes the actions in a random manner.
- After a to be specified number of actions, it will compare the yjs _operations_ if they are consistent.

You can have a look at the other types for code examples.

**Comment by cphyc** [comment]
Could you authorize http://travis-ci.org and maybe http://coveralls.io to access the repo and eventually configure them?

**Comment by dmonad** [comment]
I authorized them. I don't know why they don't build..

**Comment by dmonad** [comment]
Oh - I forgot to commit `.travis.yml`

**Comment by cphyc** [comment]
See PR #49

**Comment by cphyc** [comment]
Travis is set-up, as well as coveralls and a test-case. I'm closing and waiting for #49 to be merged.
