### ISSUE TITLE
Image embed won't be seen by peers & breaks subsequent text

### ISSUE THREAD

**Issue by Joeao** [y-js/y-richtext#111]
So I wanted to make a screen capture of simply how adding an image won't be seen by peers, however what occurred was much more dramatic: Adding text after an inserted image makes text inputs duplicate and lose positioning.

![yjs](https://cloud.githubusercontent.com/assets/2255423/12410494/5a51ada8-bea8-11e5-9a3f-599bbd703997.gif)

**Comment by dmonad** [comment]
Images are not yet working. I was waiting for 1.0 because I think it will have some breaking changes. And quills syntax for <insert image here> is really weird.

**Comment by dmonad** [comment]
But thanks for this awesome screenshot. I appreciate the effort! :+1:

**Comment by sarahm7** [comment]
hi again @dmonad this is the same issue I'm encountering right now which I raised in the YJS https://github.com/yjs/yjs/issues/281. Although the image does get synced across users now, the issue wherein the subsequent text breaks happens after uploading 2 or more images. I found that this block of code is the one breaking the subsequent text. Is it possible to remove this? I can create a PR for it

![image](https://user-images.githubusercontent.com/27810542/110410445-daa29c00-80c3-11eb-94f6-8d83b2286983.png)

**Comment by dmonad** [comment]
Hi @sarahm7,

For quite some time, Quill had an inconsistent behavior when working with newlines at the end of a document. The code you mentioned, could be removed, but then other problems would occur. I only fixed this problem in y-quill (based on yjs v13). Sorry, but  I can only accept fixes for stale packages that are definitely not breaking anything. But you are, of course, free to fork this repository.

**Comment by sarahm7** [comment]
I appreciate your fast response regarding this @dmonad. Would it be possible to know what other problems might occur? We've forked the repo now and we'll be doing testing as well after commenting that block of code. Hopefully, everything works as expected. Thanks again!
