### ISSUE TITLE
Error 'contents must be an Array of objects!' when quill has an image embedded

### ISSUE THREAD

**Issue by not-2-real** [y-js/y-richtext#114]
when I embed an image in an already bound quill object, the image is handled well, I get the images in all connected quill editors etc. But when I bind an quill object with an already embedded image I get the following error: _'contents must be an Array of objects!'_.

 The problem is that the check ```content.constructor === Object``` (https://github.com/y-js/y-richtext/blob/master/src/Richtext.js#L209) returns false while it should be true.

**Comment by dmonad** [comment]
Can you reproduce the Error on [y-js.org](y-js.org)? You can use the global variables `yQuill` / `quill` to access the Yjs instance / Quill element

**Comment by not-2-real** [comment]
while making a prototype I found out the problem is not in Y. We use [jsdom](https://github.com/tmpvar/jsdom) to run quill. While not using jsdom we don't have this problem. I'm sure the problem is not in Y so I will be looking further in the code of quill and jsdom. This issue can be closed. Sorry to bother you

**Comment by dmonad** [comment]
Sure, no problem.
