### ISSUE TITLE
Nested lists not working

### ISSUE THREAD

**Issue by f-ohler** [y-js/y-richtext#116]
There seems to be a problem with nested lists and the indentation level of list elements.
I don't really understand the behaviour of y-richtext in these situations, but it never behaves as expected, sometimes just eating the indentation information, sometimes eating the information, that the text is part of a list.

Minimal steps to reproduce using the richtext-editing example on http://y-js.org/#!/examples:

action | primary, active window | secondary, passive window
-------|------------------------|---------------------------
type "a" | `<p>a</p>` | `<p>a</p>`
click on the list icon | `<ol><li>a</li></ol>` | `<ol><li>a</li></ol>`
move cursor in front of "a", press tab | `<ol><li class="ql-indent-1">a</li></ol>` | `<p class="ql-indent-1">a</p>`

**Comment by f-ohler** [comment]
I think this is due to your code relying on the assumption that there can only be one block format active at a time. An indented list item probably has the `list` and `indent` format active at the same time.

**Comment by dmonad** [comment]
You are right, good catch!

I'm currently rewriting y-richtext for the latest Yjs version. This is going to be fixed in the next release.

**Comment by dmonad** [comment]
This should be fixed now in https://github.com/y-js/y-quill
