### ISSUE TITLE
Use Yjs types

### ISSUE THREAD

**Issue by dmonad** [y-js/y-richtext#18]
Everything, that shall be shared between users, must be on the `_model` of the respective type. For example:

RT type currently has a property `words`, that is not updated after the initialization.

Everything you do (modifying, deleting, updating..) must happen on the `_model`.

**Comment by cphyc** [comment]
I'll fix it.

**Comment by cphyc** [comment]
Same with it, I thinkg it should be closed now.

**Comment by dmonad** [comment]
yep
