### ISSUE TITLE
Propagate insertion from yjs to quilljs

### ISSUE THREAD

**Issue by cphyc** [y-js/y-richtext#2]
The RT type should propagate insertion events from yjs to quilljs, in the form of [ot-types](https://github.com/josephg/ot-types)

**Comment by cphyc** [comment]
Working on event propagation when inserting word.

**Comment by cphyc** [comment]
We should implement the new selection type before making any further progress there.

**Comment by dmonad** [comment]
This issue is to general, I'll reopen a new one.
