### ISSUE TITLE
Define correctly the deltas used in the implementation

### ISSUE THREAD

**Issue by cphyc** [y-js/y-richtext#32]
Suggestion : 

```
delta = {
  from: character,
  to: character,
  action: "set" | "delete"
  attributes: attr
}
attr = {
  key1: {
   oldValue: value | none
   newValue: value | none
  },
  key2: {…},
  key3: {…},
  …
}
value = string # can't be none
```

Undoing delta is possible under these circumstances:
- the old values of `attr` is stored **in** the delta — in `delta.attributes.anyKey.oldValue`
- the action is inverted (`set → delete` and `delete → set`)

Deltas are immutable. To modify a delta, one has to apply another delta. Two deltas are equal if they recursively have the same own properties, each of them having the same value (deep equality).

It's the work of the implementation to provide the old value of the selection as well as the new one (to discuss).

**Comment by dmonad** [comment]
When I created the Selections type, I started it in a new repository (as suggested in #25).

It is actually not necessary to save the old value of an attribute, that is handled by the algorithm.

I changed the delta as follows (no major changes)ː 

```
delta = {
  from: character,
  to: character,
  action: "select" | "unselect"
  attrs: {
    name: value
  }
}
```

I suggest to save the selections on the references as follows:
- A selection is defined as `{from: .., to: .., attrs: {..}}`
- They are saved only on list references. E.g. `y.ref(1).selection = selection`, where either `y.ref(1).selection.from === y.ref(1)` or `y.ref(1).selection.to === y.ref(1)`
- Internally, there are no overlapping selections. This makes searching for existing selections much more easy. This means that if you have a list `[1,2,3]`, and a selection `{from:1, to: 3, attrs: {c: 'blue'}}`, and apply a selection `from:2, to: 2, attrs: {c: 'red'}`. You end up with three selections: `from:1, to: 1, attrs: {c: 'blue'}`, `from:2, to: 2, attrs: {c: 'red'}`, `from:3, to: 3, attrs: {c: 'blue'}`

But just to be clear: No third party (e.g. y-richtext), should apply a delta. y-selections currently offers
`.select(from, to, attrs)` and `.unselect(from, to, attrs)` methods.
