### ISSUE TITLE
Convert the deltas of the implementation

### ISSUE THREAD

**Issue by cphyc** [y-js/y-richtext#33]
Convert the deltas from and to https://github.com/ottypes/docs deltas.

**Comment by cphyc** [comment]
Requires first #32.

**Comment by dmonad** [comment]
You can listen to the events of the new selections type. Furthermore, you can traverse through the characters (starting from y.ref(0). then call y.ret(0).next_cl / y.ret(0).prev_cl to get the next/previous element)
