### ISSUE TITLE
Inconsistencies between editor and yjs

### ISSUE THREAD

**Issue by cphyc** [y-js/y-richtext#46]
When you have 2+ editors that are concurrently editing the same document, inconsistencies appears between yjs and the editor resulting in bad behavior.

**Comment by cphyc** [comment]
This may come from the lock you put on the editor, resulting in deltas being dropped.

@edit
See PR #43 for a discussion about this point. The lock is set to prevent yjs to propagate local modifications (prevent recursion).

**Comment by cphyc** [comment]
The bug occurs when you type the text, and then move the cursor around. At some point, characters get deleted from `y.val('editor')._model.val('characters')`, even though the following functions are not called:
- `deltaHelper`
- `deleteHelper`

**Comment by dmonad** [comment]
It was a problem of Yjs. I fixed it.
