### ISSUE TITLE
Optimize indexing of words

### ISSUE THREAD

**Issue by cphyc** [y-js/y-richtext#5]
Finding and adding words should work faster than in `O(n)`.
Maybe we could use a binary tree to represent the list of words, each leaf being decorated by number of children on each side?

**Comment by dmonad** [comment]
I agree. But we should not create another data structure. The list type actually supports relative addressing (so you can move one word forward/backwards from the current position). But this is not yet implemented well. I this is implemented, then this could make things much more efficient.

I'll see how we can improve that.

**Comment by cphyc** [comment]
Ok ; it is also worth noting that most of the jumps are from the cursor positions and that the implementation should be aware of that. If we save the cursor position, then we can do a local search around the position (at left and right). If no success, then we can just do a linear search over all the words (costing `O(position of the word)`).

**Comment by dmonad** [comment]
I actually want to avoid to have another data structure that holds all the characters.

I haven an idea: You can use the cursor positions as they are described in #9 to insert characters efficiently. 
When a user inserts something, you just insert a character at the current cursor position of that user. Still, you have to find the position (as an integer) to pass it to quilljs. What you can do is the following:
- get the current cursor position from quilljs (will return it as an integer)
- insert the new character/word at this position

**Comment by dmonad** [comment]
Current implementation is fast enough. Some time ago [the kate editor](http://kate-editor.org/) explained very well how they store text data in their editor. In the future I plan to copy some of their concepts. For now, y-richtext should be fast enough.
