### ISSUE TITLE
initialize quill with an existing editor

### ISSUE THREAD

**Issue by dmonad** [y-js/y-richtext#61]
Currently, the example overwrites the editors content with an empty document. But it should be possible to create y-richtext like this:

```
new Y.Richtext(quill)
```

the y-richtext will be initialized with the existing content of quill, therefore, the content of quill won't be overwritten.

**Comment by cphyc** [comment]
How far are you on this issue?

**Comment by dmonad** [comment]
On `initial_editor` you can do this already.

```
new Y.Richtext("QuillJs", quill)
```
