### ISSUE TITLE
Image get transformed to "!"

### ISSUE THREAD

**Issue by cphyc** [y-js/y-richtext#68]
The result of the two following operations:

```
{ ops: [
           { retain: position},
           { insert: 1}
       ]
}
# and then
{ ops: [
           { retain: position},
           { retain: 1, attributes: {image: "someimageurl.png"}}
       ]
}
```

has not the same result as

```
{ ops: [
           { retain: position},
           { insert: 1, attributes: {image: "someimageurl.png"}}
       ]
}
```

The first one results in a weird `!` and no image, while the second one gives the image.

**Comment by cphyc** [comment]
I made a hack by adding a `attributes: {image: "http://" }` when missing for an `{insert : 1}`. There's an open issue on quilljs (https://github.com/quilljs/quill/issues/347).

**Comment by dmonad** [comment]
I fixed this in the `initial_editor` branch. In the current master branch, quill receives two deltas on startup:
1. one for the text
2. one for the selections

But now I transform text+selections into one delta. Therefore, this cannot happen anymore.
