### ISSUE TITLE
Write documentation

### ISSUE THREAD

**Issue by cphyc** [y-js/y-richtext#7]
Write a documentation to explain how to bind OT-editors to y-rich-text.

**Comment by dmonad** [comment]
I'll do that.
- Furthermore, I'll update the README
- the license
- create an example directory (with quilljs example)

**Comment by dmonad** [comment]
I implied in the documentation how you _should_ bind a rich text type to an editor.

```
y.val("editor").bind(quill)
```

-- It should be as easy as that

**Comment by dmonad** [comment]
I wrote in the last pull requet how the editor should be bound to the rich text type. So I close this.
