### ISSUE TITLE
Quilljs and yjs diverges

### ISSUE THREAD

**Issue by cphyc** [y-js/y-richtext#75]
You can get a divergence by deleting `Word` or the first `e` in the initial example.

**Comment by cphyc** [comment]
When you remove the `e`, the selections keep the same length and therefore get shifted one character to the right.

**Comment by cphyc** [comment]
After some investigation, it seems that `editor.getDelta()` is not working correctly, since a lately joined browser is visually correctly synchronized, whereas `editor.getDelta()` has not the same output as `quill.getContents()`

**Comment by dmonad** [comment]
Found the problem. Hard to explain, I'll just fix it

**Comment by dmonad** [comment]
Pull y-selections again, then it works :)
