### ISSUE TITLE
Authorship

### ISSUE THREAD

**Issue by cphyc** [y-js/y-richtext#8]
Y-rich-text should support authorship.

**Comment by dmonad** [comment]
To what extend?

My idea is to check all `words` for the creator (with `word._model.uid.creator`) and then return a list of selections that specify the creator of the text. It should be easily possible to parse this list in such a way that you can show it in the respective (i.e. quilljs) editor.

**Comment by cphyc** [comment]
If we activate authorship from quilljs, then an insertion looks like

```
[{ value: 'newText', attributes: { author: 'id-1234' } }]
```

Therefore, there's not a lot to do on our side, except make sure it works, but it's already handled by the selections.

**Comment by cphyc** [comment]
I'm working on it.

**Comment by cphyc** [comment]
I'm writing a **basic** support for authorship for the cursor, so that we can bind a (real) name to a cursor. I'm not saving the authorship of each included words because I don't think it's a priority now.
