### ISSUE TITLE
Index error

### ISSUE THREAD

**Issue by cphyc** [y-js/y-richtext#80]
When inserting and moving the cursor quickly after, you might try to access a character _before_ the synchronization between quill and yjs has occurred, resulting in an `Error: Invalid index` and the cursor is not moved.

However, it does not break anything and is therefore a minor bug.

**Comment by cphyc** [comment]
Can't reproduce the bug anymore.

**Comment by dmonad** [comment]
Should not happen anymore. The yjs content is ìnserted as one list of operations now (with `quill.setContent(ops)`)
