### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by cphyc** [y-js/y-richtext#81]
When running this function with `n=10 000`, you get at some point the error `RangeError: Maximum call stack size exceeded` because (it seems that) `applyDelete` is called too many time recursively. You get this if, during the moving of the first cursor you move the cursor in another instance.

``` js
function fuzzy_cursor(n) {
    for (var i = 0; i < n; i ++) {
        var m = Math.floor(Math.random() * quill.getLength());
        quill.setSelection(m, m);
    }
}
```

**Comment by cphyc** [comment]
The good news is, I think it's quite hard to fell under those conditions. The bad news is, that makes yjs crash and it might happen when loading a document with a long history.

**Comment by dmonad** [comment]
This is actually a good one. This is a problem of Yjs. 'll address it soon. Shouldn't be too hard to fix.

**Comment by dmonad** [comment]
No more call stack problems with yjs > 0.7 (at least I hope so).
