### ISSUE TITLE
new bug ..

### ISSUE THREAD

**Issue by dmonad** [y-js/y-richtext#83]
Write a long text that is "HUGE" formatted. Go in the middle of that text, and perform two 'breaks' (press enter). Then type something. If you reload the page, it will be displayed differently.

**Comment by cphyc** [comment]
I can't reproduce the bug...

**Comment by dmonad** [comment]
The problem is because we understood quill wrong:
Assume we have the word **quill**. Now we insert _x_ between u and i. Then quill will create

```
delta.insert = "x"
delta.attributes = {bold: true}
```

But when we insert a new line between u and i. Quill creates

```
delta.insert = "enter"
delta.attributes = {}
```

So we are not supposed to make text bold in the new line.

this is not a specific problem of the initial_editor branch.

**Comment by cphyc** [comment]
Ok!
