### ISSUE TITLE
Drag and drop of image bug

### ISSUE THREAD

**Issue by cphyc** [y-js/y-richtext#92]
When drag and dropping an image into the editor after initialization, Yjs sends first `{retain: XXX}, {insert:1}` and then `{retain: XXX}, {retain: 1, attributes:{image: 'the.url.com'}}`.
However, quill does not support `{insert: 1}` and therefore crashes.

The workaround would be to add to `{insert: 1}` `attributes: {image: 'http://'}` to prevent quill from crashing.

**Comment by cphyc** [comment]
Can you confirm that it's working for you?

**Comment by dmonad** [comment]
I don't think that this is the "right" way to do it. I found some indices that Quill has problems with the fact that y-richtext throws first insert, then the retain+attributes event. So maybe we can find a more general solution for this
