### ISSUE TITLE
Inconsistencies when two users insert something concurrently

### ISSUE THREAD

**Issue by dmonad** [y-js/y-richtext#96]
Yjs will be on the correct state. But it seems that Quill does not process everything that is sent from y-richtext. It is currently unclear to my what the exact problem is, because it is hard to debug

**Comment by cphyc** [comment]
From what I saw, it seems that quill is unable to process correctly
multiple inputs that are sent "concurrently". Could it be because of the
fact that events may not arrive in the order they were sent?

**Comment by dmonad** [comment]
The reason was that quill does not throw synchronous events. I fixed it in a previous commit
